### ISSUE TITLE
Error show after install - Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Serial_Numbers_Admin_Menus' does not have a method 'serial_numbers_page' in G:\server7\htdocs\wc-min-max-quantities\wp-includes\class-wp-hook.php on line 287

### ISSUE THREAD

**Issue by mahedihasannoman** [pluginever/wc-serial-numbers#103]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Serial_Numbers_Admin_Menus' does not have a method 'serial_numbers_page' in G:\server7\htdocs\wc-min-max-quantities\wp-includes\class-wp-hook.php on line 287

**Comment by sultann** [comment]
Thats okay I am not done yet.
