### ISSUE TITLE
Support for wp all export plugin

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#123]
need support for wp all export pro plugin

**Comment by jjrbits** [comment]
From a customer: 

We export, in our management software and using "WP All Export Pro" and "Store exporter deluxe", the orders and activation codes of the eboxes that we sell.
For a few days now, we no longer have access to the "activation code" field (serial key) from these tools. Would you have an explanation? Can you help us please?
For your information, if I manually launch an export from your tool, everything is ok. So, if necessary, we can use your tool if we can automate it or call it via API. Do you have any detailed documentation on this please?

**Comment by jjrbits** [comment]
https://github.com/pluginever/wc-serial-numbers-pro/issues/143
