### ISSUE TITLE
Activation error when same instance used multiple time for same serial numbers

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#158]
**Describe the bug**
When activating serial numbers with multiple activations, if one instance is given for multiple activations then the first activations will work. The second time when providing the same instance, serial number activations will not work.

**To Reproduce**
1. Try to activate the serial numbers using api
2. Provide a user-defined instance like `test-instance` for the first time.
3. Provide the same instance for the second time.
4. First activations will be worked. The second attempt will not work.

**Expected behavior**
In the API response, provide an error message that the same instance is provided. Provide a new instance or use a plugin-created instance.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by syedladen** [comment]
On the new 1.4.9 and 1.2.4 versions, one instance is for one activation. 

It means, one instance cannot be used for multiple activations, thus it has to be unique every time.
