### ISSUE TITLE
Feature Request from a customer

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#162]
1. An option to add links to the serial numbers which will be added in product-edit-screen.
2. If the URL exists, then serial numbers will show as links (in email, thank-you, and my-account page)
3. An option to add notes in template settings in serial numbers settings.
4. This note will be shown after serial numbers in the order confirmations email.
5. For the URL on the product edit screens, there will be an option to give placeholders.

**Comment by jjrbits** [comment]
https://github.com/pluginever/wc-serial-numbers/issues/188
