### ISSUE TITLE
Check order completion email not sending serial numbers when vpn is activated

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#191]
**Describe the bug**
Customer message: 

> I believe the issue arose due to the VPN I have been running in the background. This appears to have blocked both order confirmation e-mails (which also includes the purchased serial number) from being sent as
> well as displaying the purchased serial number itself in the online order confirmation display.
> 
> When I suspended my VPN then both the online order confirmation display and the corresponding e-mail were sent as expected.
> 
> I want to do a few more tests for consistency but could you provide me with an explanation as to why the use of a VPN would hinder your plugin from displaying the purchased serial number as well as preventing WooCommerce
> from sending out the corresponding e-mail.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jjrbits** [comment]
not directly related to wcsn.
