### ISSUE TITLE
Support link is wrong

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#197]
**Describe the bug**
The `Submit a ticket` button link is not correct. Right now it is redirecting to the contact us page but it should be the support page.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://www.loom.com/i/e90e92305ea3496b99ac2ba3ef0e11ac

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bappi** [comment]
Fix included here: https://github.com/pluginever/wc-serial-numbers/pull/205

**Comment by Bappi** [comment]
Merged.
