### ISSUE TITLE
Actions links rearrange

### ISSUE THREAD

**Issue by sudipto-me** [pluginever/wc-serial-numbers#199]
**Describe the bug**
Action links needs to be rearranged and make them like woocommerce or other plugins so that all of our plugins will be in same order.

**To Reproduce**
1. Go to plugin listing page
2. Check woocommerce action links 
3. Scroll down to wc-serial-numbers action links
4. See errors

**Expected behavior**
They are need to be the same order like woocommerce.

**Screenshots**
https://www.loom.com/i/b72934f62ae24857b1af728ffa686379

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bappi** [comment]
PR https://github.com/pluginever/wc-serial-numbers/pull/206

**Comment by Bappi** [comment]
Merged.
