### ISSUE TITLE
Low stock notification email not working

### ISSUE THREAD

**Issue by jjrbits** [pluginever/wc-serial-numbers#246]
When the product stock is low, it's supposed to send a notification email. It's not sending.

**Comment by syedladen** [comment]
**Correction/Feature Request/Issue**

The 'Stock notification' option refers to the settings that it will 'send a notification email if product stock is low.'

But we all know that product stock low notification is maintained by WooCommerce itself if anyone enters the 'Low stock threshold' by inventory.

Our plugin should offer/feature something like 'Sends notification emails when Serial keys/License keys stock is low for a particular serial number enabled product.
