### ISSUE TITLE
Activations link does not work while clicking the number.

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#267]
**Describe the bug**
For activations such as 1/5, the link does not work when clicking the number.

**To Reproduce**
1. Go to the Serial Numbers tab and see the activation row like 0/1.
2. Click on the link embedded on 0/1
3. See error - Sorry, you are not allowed to access this page.

**Expected behavior**
A dedicated page should open and allow access.

**Screenshots**
<img width="915" alt="image" src="https://user-images.githubusercontent.com/113977361/216890603-51c73023-d9ba-40e6-b3ea-5a2f230276bb.png">

**Comment by sultann** [comment]
What version are you having the problem with? The latest version does not have that column on the serial numbers list table.

**Comment by jjrbits** [comment]
It's still there in the latest version, the link is incorrect that's why it's showing the error 

![CleanShot 2023-02-20 at 12 22 23](https://user-images.githubusercontent.com/7249823/220027618-6d5e3bab-1de0-40ef-931f-4cd01367f8b6.png)

**Comment by jjrbits** [comment]
fixed
