### ISSUE TITLE
Serial Number is not showing while exporting orders with other Export Plugins

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#269]
**Describe the bug**

Advance Order Export for WooCommerce plugin does not export the serial keys. Only showing the serial key source dummy text, not the serial number.

**To Reproduce**

1. Go to Advance Order Export for WooCommerce and export fields including serial keys.

2. After exporting the file, you'll see that the serial keys are not being exported. But the serial key source fields are present.

**Expected behavior**

The serial keys should show in the export file.

**Screenshots**
![image](https://user-images.githubusercontent.com/113977361/223385870-1c13060f-06b2-4073-a490-6d408116c01d.png)

![image](https://user-images.githubusercontent.com/113977361/223385775-afac2e5f-5e27-45d9-bb02-551cc62dd8c2.png)

**Comment by jjrbits** [comment]
https://github.com/pluginever/wc-serial-numbers-pro/issues/143
