### ISSUE TITLE
Serial numbers should be replaced with Serial Keys

### ISSUE THREAD

**Issue by jjrbits** [pluginever/wc-serial-numbers#279]
In settings 

![CleanShot 2023-03-28 at 14 06 36](https://user-images.githubusercontent.com/7249823/228171692-f7386d9a-4d33-4e5b-8cdd-f32a95906b95.png)

**Comment by jjrbits** [comment]
![CleanShot 2023-03-28 at 14 25 28](https://user-images.githubusercontent.com/7249823/228175858-92335594-c9a1-444c-aff3-11846e3d81e3.png)

**Comment by syedladen** [comment]
'Serial Numbers' text & Plugin Name are yet to be replaced from the Tools menu.

<img width="1680" alt="Screenshot 2023-03-29 at 3 16 25 PM" src="https://user-images.githubusercontent.com/113977361/228504725-ce800069-193b-4c84-b78d-81bd0b534c3a.png">

**Comment by jjrbits** [comment]
Need to replace this one in Tools-> API section https://prnt.sc/uCBf8SP7QHTN
