### ISSUE TITLE
'Serial Numbers' text & Plugin Name yet to be replaced from Tools menu

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#288]
**Screenshots**

<img width="1680" alt="Screenshot 2023-03-29 at 3 16 25 PM" src="https://user-images.githubusercontent.com/113977361/228490546-c085d9a3-56e0-4464-84f4-3834504eeae0.png">

**Comment by jjrbits** [comment]
there's another open issue for that
