### ISSUE TITLE
General search query on the report page

### ISSUE THREAD

**Issue by owadud** [pluginever/wc-serial-numbers#293]
*** Need a search field on the reports page***

In our report section, we can see the product's serial key stock. But we have only one filter option which is search by product.

That is for only one item.  Previously we have a more helpful search option. So we need a search bar on the report page.

https://prnt.sc/cs0BIT9ca7hS

**Comment by sultann** [comment]
@owadud Please check and let me know.

**Comment by owadud** [comment]
solved.
