### ISSUE TITLE
When someone buys more than 20 serial number enabled product in 1 order, they only see 20 products/serial keys

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#295]
**Describe the bug**
If someone buys more than 20 products, the table shows only 20 columns and not the rest of them.

**To Reproduce**
1. You buy a product of more than 20 on a single order. Let's say 30, you'll only see 20.
2. See error on test.pluginever.com - https://test.pluginever.com/checkout/order-received/179/?key=wc_order_uqRSjynPs0zp4

**Expected behavior**
It should show all the products including every field.

**Comment by sultann** [comment]
@syedladen ready for testing, please let me know the testing result.

**Comment by syedladen** [comment]
The issue has been re-tested on test.pluginever.com

It is now resolved.
