### ISSUE TITLE
Action 'Edit' is not working for variable products on Report menu. 

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#296]
**Describe the bug**

On the report menu, the variable product 'edit' link is not working.

**To Reproduce**

1. Go to Serial Number>Reports on test.pluginever.com
2. Check a variable product, for example, woo-hoodie-blue-logo.
3. Click on the 'edit' link under the action tab. 
4. It will not work/stays on the page.

**Expected behavior**

Should be able to edit the product.

**Screenshots**

<img width="694" alt="image" src="https://user-images.githubusercontent.com/113977361/230303735-a5a7cc14-5551-4c4e-8cad-e318a2b67ec2.png">

**Comment by sultann** [comment]
@syedladen, Please check and let me know.

**Comment by syedladen** [comment]
The issue had been checked on test.pluginever.com

The issue has been resolved.
