### ISSUE TITLE
Serial Numbers text should be changed to Serial Keys on Variable products section

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#307]
**Describe the bug**
Serial Numbers text should be changed to Serial Keys on the specific areas.

**To Reproduce**
1. Go to any variable products
2. Click on edit
3. Scroll down to Serial Number settings

**Screenshots**
<img width="496" alt="image" src="https://user-images.githubusercontent.com/113977361/231569564-75cabde1-9955-45fe-8a6f-e935d41b45da.png">

**Comment by relevenx** [comment]
it's already fixed in 1.5.4
