### ISSUE TITLE
Bulk remove activations

### ISSUE THREAD

**Issue by sultann** [pluginever/wc-serial-numbers#312]
I often get requests from users to reset their key activation instances. I don't want them to be able to do this on the front end - and the instance IDs are secret, they have to manually submit the request to me. So to do this, I currently have to do the following steps:

- find order with their email.
- find the key associated with that order.
- go to the serial key to search for the ID of that key.
- go to Activation to look up instances activated by that ID.
- delete activation instances.

Is there a way to do it faster? For example in the Edit serial key section, can you add a button like "Remove all activation instance" or something like that? If possible, that would be great.

**Comment by owadud** [comment]
This issue is solved.
