### ISSUE TITLE
Search is not working on Serial Keys Menu and Activation Menu

### ISSUE THREAD

**Issue by syedladen** [pluginever/wc-serial-numbers#353]
Search is not working properly on Serial Keys and Activation Menu on MySQL version 8.0.16.

<img width="756" alt="image" src="https://github.com/pluginever/wc-serial-numbers/assets/113977361/0409d744-67ea-45de-adb0-34937c29ccf7">
<img width="758" alt="image" src="https://github.com/pluginever/wc-serial-numbers/assets/113977361/4e413c05-2527-432b-b450-ed7bc7e0d440">

**Comment by sultann** [comment]
@syedladen please check and get back to me if it works now or not.

**Comment by owadud** [comment]
Issue fixed.
