### ISSUE TITLE
Compatible issue with WooCommerce HPOS

### ISSUE THREAD

**Issue by owadud** [pluginever/wc-serial-numbers#402]
**Describe the bug**

The keys column is missing on the order table and also bulk action: "Add serial keys, Remove serial keys" 

![image](https://github.com/pluginever/wc-serial-numbers/assets/34317276/1a2ba0d1-3a17-4ce4-98cc-224738786882)

**To Reproduce**

1.  Go to 'Orders'
2.  See the issue

**Comment by lamb560** [comment]
issue is still not resolve..... Still waiting....
