### ISSUE TITLE
Key is not assigned with order form key edit page

### ISSUE THREAD

**Issue by devsabbirhossain** [pluginever/wc-serial-numbers#439]
- Order is not assigned with keys

1. Before Saving key 

![Screenshot 2024-09-15 at 2 53 53 PM](https://github.com/user-attachments/assets/b44c9743-bc3d-4234-837e-20d83350b7c3)

2. After Save key

![Screenshot 2024-09-15 at 2 54 05 PM](https://github.com/user-attachments/assets/3a7177e4-0dc5-4ef1-930e-a19bbd34f8c3)

**Comment by kawsarahmedr** [comment]
The status should be "sold" to assign the key corresponding to the order.
